### ISSUE TITLE
html5 inputStream + outputStream connection

### ISSUE THREAD

**Issue by Archethect** [tommedema/NodeBasicFFmpeg#2]
This is not an issue, but a question I want to ask.
Do you know if it is possible to livestream a certain file via html5 and websockts to the inputstream of NodeBasicFFmpeg? 
Also, if the previous question is possible, can you use the outputstream as an url for playing in an html5 audio-tag? 
Basically I would like to create some sort of Icecast-clone that would make it possible for clients to play songs, which can in realtime be listened by other clients in html5 with node.js as a server.

**Comment by tommedema** [comment]
1. websockets force strings, so you can only transfer binary data disguished in a string (horrible performance wise). Also, a browser does not allow you to get to the binary data of a file on the client side.
2. sure, just perform the request on the client side and pipe the stream to the request

**Comment by Archethect** [comment]
Ow, ok. I thought it was possible to get the binary data of a file in the browser by using FileReader.readAsBinaryString. But that is a string indeed. How would you suggest to stream a media file from the client-side (html5) to the inputstream than, rather than using a predefined file located at the server-side?

**Comment by tommedema** [comment]
You use a normal form for file uploads (will arrive as a POST request), use something like node-formidable to parse the incoming stream.

**Comment by Archethect** [comment]
Ok, thanks! I'll take a closer look at node-formidable :)
